language: rust
rust: 1.36.0
script: ci/run.bash
cache:
    directories:
        - target
        - $HOME/ritual_temp_test_dir/test_full_run/workspace/target

matrix:
    include:
        - os: linux
          dist: bionic
        - os: osx
        - os: windows
