__common: &common
    language: rust
    rust: 1.36.0
    script: ci/run.bash
    cache:
        directories:
        - target

matrix:
    include:
    -   <<: *common
        os: linux
        dist: trusty
    -   <<: *common
        os: osx
    -   <<: *common
        os: windows
