__common: &common
    language: minimal
    script: scripts/travis/run.bash
    cache:
        directories:
            - target
            - $HOME/ritual_temp_test_dir/test_full_run/workspace/target

matrix:
    include:
        -   <<: *common
            os: linux
            dist: trusty
#    -   <<: *common
#        os: osx
#    -   <<: *common
#        os: windows
