[package]
name = "rust_qt_examples"
version = "0.0.0"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
edition = "2018"

[dependencies]
qt_core = "0.3.0"
qt_gui = "0.3.0"
qt_widgets = "0.3.0"
qt_ui_tools = "0.3.0"
qt_3d_core = "0.3.0"
qt_3d_render = "0.3.0"
qt_3d_input = "0.3.0"
qt_3d_logic = "0.3.0"
qt_3d_extras = "0.3.0"
qt_charts = "0.3.0"

[patch.crates-io]
qt_core = { path = "../../qt_workspace/out/qt_core" }
qt_gui = { path = "../../qt_workspace/out/qt_gui" }
qt_widgets = { path = "../../qt_workspace/out/qt_widgets" }
qt_ui_tools = { path = "../../qt_workspace/out/qt_ui_tools" }
qt_3d_core = { path = "../../qt_workspace/out/qt_3d_core" }
qt_3d_render = { path = "../../qt_workspace/out/qt_3d_render" }
qt_3d_input = { path = "../../qt_workspace/out/qt_3d_input" }
qt_3d_logic = { path = "../../qt_workspace/out/qt_3d_logic" }
qt_3d_extras = { path = "../../qt_workspace/out/qt_3d_extras" }
qt_charts = { path = "../../qt_workspace/out/qt_charts" }

