[package]
name = "qt_macros"
version = "0.1.0"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

